title: Netty
base_url: http://netty.io/
google_analytics: UA-95307-5

stableReleaseVersion: 3.2.6.Final
stableReleaseDate: 22-Oct-2011
#unstableReleaseVersion: 4.0.0.Alpha1
#unstableReleaseDate: 25-Dec-2011

