title: Netty
base_url: http://netty.io/

google_analytics: UA-95307-5

disqus: netty0

stableReleaseVersion: 3.4.2.Final
stableReleaseDate: 27-Apr-2012

#unstableReleaseVersion: 3.4.0.Beta1
#unstableReleaseDate: 04-Apr-2012

