title: Netty
base_url: http://netty.io/

google_analytics: UA-95307-5

disqus: netty0

stableReleaseVersion: 3.5.0.Final
stableReleaseDate: 08-Jun-2012

#unstableReleaseVersion: 3.5.0.Beta1
#unstableReleaseDate: 25-May-2012

